#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


// const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
// 	[0] = LAYOUT_ortho_5x15(
// 	    KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSLS, KC_GRV,
// 	    KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSPC, KC_DEL,
// 	    KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_ENT, KC_PGUP,
// 	    KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(1), KC_UP, KC_PGDN,
// 	    KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_SPC, KC_RALT, KC_RCTL, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

// 	[1] = LAYOUT_ortho_5x15(
// 	    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
// 	    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
// 	    RGB_MOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
// 	    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
// 	    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, QK_BOOT)
// };

enum my_keycodes {
	CAPS = SAFE_RANGE
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_5x15(
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,QK_MAKE,QK_BOOT,
		XXXXXXX,KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,   XXXXXXX,XXXXXXX,XXXXXXX,KC_Y,   KC_U,   KC_I,   KC_O,   KC_P,   KC_LBRC,
		CAPS   ,KC_A,   KC_S,   KC_D,   KC_F,   KC_G,   XXXXXXX,XXXXXXX,XXXXXXX,KC_H,   KC_J,   KC_K,   KC_L,   KC_SCLN,KC_QUOT,
		XXXXXXX,KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   XXXXXXX,XXXXXXX,XXXXXXX,KC_N,   KC_M,   KC_COMM,KC_DOT, KC_MINS,KC_BSLS,
		XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,KC_LSFT,KC_SPC ,MO(1)  ,XXXXXXX,MO(2)  ,KC_ENT ,KC_BSPC,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX
	),
	[1] = LAYOUT_ortho_5x15(
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,OSM(MOD_LGUI),OSM(MOD_LALT),OSM(MOD_LSFT),OSM(MOD_LCTL),_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______
	),
	[2] = LAYOUT_ortho_5x15(
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,
		_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______,_______
	)
};
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


bool process_record_user(uint16_t keycode, keyrecord_t* record) {
	static uint16_t last_caps_press_time = 0;
	static int8_t caps_press_count = 0;
	static bool caps_pressed = false;
	static bool caps_used_as_lctl = false;
	switch (keycode) {
		case CAPS:
			if (record->event.pressed) {
				caps_pressed = true;
				if (timer_elapsed(last_caps_press_time) > 200 || caps_used_as_lctl) {
					caps_press_count = 0;
					caps_used_as_lctl = false;
				}
				switch (caps_press_count) {
					case 0:
						register_code(KC_LCTL);
						break;
					case 1:
						SEND_STRING(">");
						break;
					default:
						break;
				}
				caps_press_count++;
				last_caps_press_time = timer_read();
			} else {
				caps_pressed = false;
				switch (caps_press_count) {
					case 1:
						unregister_code(KC_LCTL);
						if (timer_elapsed(last_caps_press_time) <= 200 && !caps_used_as_lctl) {
							tap_code(KC_ESC);
						}
						break;
					default:
						caps_press_count = 0;
						break;
				}
			}
			return false;
		default:
			if (record->event.pressed && caps_pressed == true && caps_press_count == 1) {
				caps_used_as_lctl = true;
			}
			return true;
	} 
}


// td_state_t cur_dance(tap_dance_state_t* state) {
// 	if (state->count == 1) {
// 		if (state->interrupted || !state->pressed) return TD_SINGLE_TAP;
// 		else return TD_SINGLE_HOLD;
// 	} else if (state->count == 2) {
// 		if (state->interrupted || !state->pressed) return TD_DOUBLE_TAP;
// 		else return TD_DOUBLE_HOLD;
// 	} else {
// 		return TD_UNKNOWN;
// 	}
// }

// static td_tap_t xtap_state = {
// 	.is_press_action = true,
// 	.state = TD_NONE
// };

// static bool is_holding_ctl = false;

// void x_released(tap_dance_state_t *state, void *user_data) {
// 	switch (state->count) {
//   	case 1:
// 			if (!state->pressed) tap_code16(KC_ESC); break;
// 		default: break;
//   }
// }

// void x_finished(tap_dance_state_t *state, void *user_data) {
// 	xtap_state.state = cur_dance(state);
// 	switch (xtap_state.state) {
// 		// case TD_SINGLE_TAP: register_code(KC_ESC); break;
// 		case TD_SINGLE_HOLD: register_code(KC_LCTL); break;
// 		case TD_DOUBLE_TAP: register_code(KC_LSFT); register_code(KC_DOT); break;
// 		default: break;
// 	}
// }

// void x_reset(tap_dance_state_t *state, void* user_data) {
// 	switch (xtap_state.state) {
//   	// case TD_SINGLE_TAP: unregister_code(KC_ESC); break;
// 		case TD_SINGLE_HOLD: unregister_code(KC_LCTL); break;
// 		case TD_DOUBLE_TAP: unregister_code(KC_DOT); unregister_code(KC_LSFT); break;
// 		default: break;
//   }
// 	xtap_state.state = TD_NONE;
// }



// tap_dance_action_t tap_dance_actions[] = {
// 	[ESC_CTL] = ACTION_TAP_DANCE_FN_ADVANCED_WITH_RELEASE(NULL, x_released, x_finished, x_reset)
// };
